# general
seed: 2020
state: INFO
use_text: True
reproducibility: True
checkpoint_dir: 'saved'
show_progress: True

log_wandb: False
wandb_project: 'REC'
MAX_ITEM_LIST_LENGTH: 50
MAX_TEXT_LENGTH: 64

data_path: ../dataset/                       # dataset path
dataset: Pixel200K                        # dataset name
test_dataset: Pixel200K                        # dataset name

text_path: text_path # Use absolute path
text_keys: ['title', 'tag', 'description']

item_prompt: 'Compress the following sentence into embedding: '
item_emb_token_n: 1

# training settings
epochs: 10
train_batch_size: 8
optim_args: {
  learning_rate: 1e-4,
  weight_decay: 0.01
}
scheduler_args: {
  type: cosine,
  warmup: 0.1
}

# eval settings
eval_batch_size: 256
topk: [5,10,50,200]
metrics: ['Recall', 'NDCG']
valid_metric: NDCG@200
metric_decimal_place: 7
eval_step: 1 
stopping_step: 5

strategy: ddp
precision: bf16-mixed